" Plugins
call plug#begin('~/.vim/plugged')

Plug 'rakr/vim-one'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdcommenter'

call plug#end()

" Themes
colorscheme one
set background=dark

" Airline
let g:airline_symbols_ascii=1
let g:airline_theme='base16'
set ttimeoutlen=25

" Commenter
filetype plugin on

" Graphical configuration
syntax on
set number
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set cursorline

" Search
set hlsearch
set smartcase
set ignorecase
set incsearch

" Indentation
set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

" Input
set undolevels=1000
set backspace=indent,eol,start
set wildmenu
set wildmode=list:longest
set mouse=a

" L/R cursor to previous and next lines
set whichwrap+=<,h
set whichwrap+=>,l
set whichwrap+=[,]

" Shared clipboard
set clipboard=unnamedplus

"" Bindings

" Ctrl-X Ctrl-S save in insert
inoremap <C-x><C-s> <C-\><C-o>:w<cr>

" Tabs
nmap <silent> <C-n> :tabedit<cr>
nmap <silent> <C-q> :q!<cr>
nmap <silent> <C-z> :tabprevious<cr>
nmap <silent> <C-x> :tabnext<cr>
