#!/usr/bin/env bash

service=NetworkManager.service
com="systemctl restart $service"
echo "Restarting $service..."
if [ $UID == 0 ]; then
	$com
else
	[ -z "${SUDO-}" ] && SUDO=sudo
	$SUDO $com
fi

[ $? == 0 ] && ( echo "Starting network test..."; $HOME/scripts/pingtest )