if [[ "$TERM" == "xterm-kitty" ]]; then
	# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
	# Initialization code that may require console input (password prompts, [y/n]
	# confirmations, etc.) must go above this block; everything else may go below.
	if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
	fi

	theme=/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
	[[ ! -f $theme ]] || source $theme
	
	# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
	[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
fi

source ~/.profile

alias ll="ls -l"
alias la="ls -al"
alias c="clear"
alias pac="sudo pacman"
alias aur="pikaur"
alias sysd="sudo systemctl"
alias status="journalctl -xeu"
alias pgrepv="ps -ax | grep -v 'grep' | grep"
alias setrandr="touch $RANDRLOCK >/dev/null; \
                autorandr -l"