source ~/.profile
source ~/.dircolors

alias ll="ls -l"
alias la="ls -al"
alias c="clear"

alias xbi="sudo xbps-install"
alias xbr="sudo xbps-remove"
alias xbq="xbps-query"
alias dmesg="sudo dmesg"
alias sv="sudo sv"
alias svim="sudo -E vim"

alias svuser="svuser $SVDIR_USER"
alias tmtab="tmux -L tabbed -f $HOME/.tmux/sessions/tabbed"
alias psx="ps -ax | grep -v 'grep' | grep"
alias setrandr="touch $RANDR_LOCK >/dev/null; \
                autorandr -l"
