#!/usr/bin/env bash

EXEC=$(basename $0)

usage() {
	expand --tabs=4 <<-EOF
	usage: $EXEC [options] DIRECTORY
	Opens a shell with environment variables reset to a HOME folder at the specified directory.

	options:
	  -h			show usage
	EOF
}

while getopts ":h:" opt; do
	case $opt in
		h)	usage; exit 0 ;;
		*)	echo "Invalid option -$OPTARG, run \`$EXEC -h\` to show usage" >&2;
			exit 1 ;;
	esac
done

shift $((OPTIND-1))
[ -n "${1-}" ] || (echo "Directory not specified" >&2; exit 1)

PWD=$(pwd)
DIRECTORY="$PWD"/"$1"

NEWENV="
HOME="$DIRECTORY"
XDG_CONFIG_HOME="$DIRECTORY"/.config
TERM=$TERM
"

mkdir -p "$DIRECTORY" && \
/usr/bin/env -i -C "$DIRECTORY" $NEWENV bash