#!/usr/bin/env bash

#-------------------------------#
# Display current cover         #
#-------------------------------#

source "$(ueberzug library)"

UID=$(id -u)
COVER="/tmp/ncmpcpp-$UID/cover.png"
X_PADDING=0
Y_PADDING=0

function add_cover() {
    ImageLayer::add [identifier]="cover" [x]="$X_PADDING" [y]="$Y_PADDING" [path]="$COVER"
}

function remove_cover() {
    ImageLayer::remove [identifier]="cover"
}

function you_wait() {
    while inotifywait -q -q -e close_write "$COVER"; do
        add_cover
    done
}

run() {
    clear
    stty -echo
    tput civis

    while [ ! -f "$COVER" ]; do
	sleep 0.5
    done

    ImageLayer 0< <(
	add_cover
	you_wait
    )

    exec $0
}

restore() {
    if [[ -t 0 && -n "${LAST_STTY-}" ]]; then
        stty "$LAST_STTY"
    fi
    tput cnorm
    
    exit
}

trap restore SIGINT SIGTERM
LAST_STTY=$(stty -g)
run
restore
