#!/bin/sh

export USER="$(dirname $0 | awk -F 'runsvdir-' '{ print $2 }')"
test -n "$USER" || exit

export HOME="/home/$USER"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.service"

exec chpst -u "$USER:$groups" runsvdir "$svdir"
