#!/usr/bin/env bash

read -r -d '' LINES <<-'EOF'
0 0 * * * $HOME/.local/scripts/launchenv relaunch schedule_themes
EOF

crontab -l \
    | grep -i 'schedule_themes' \
    | echo "$LINES" \
    | crontab -