#!/usr/bin/env bash

LOCSTRING="$(fmt_helio_location < $XDG_CONFIG_HOME/locations/current)"
HELIO="$(which heliocron)"
COM="$(which settheme)"

read -r -d '' LINES <<-EOF
0 0     * * * $HELIO $LOCSTRING wait --event sunrise;    $COM light
0 12    * * * $HELIO $LOCSTRING wait --event sunset;     $COM dark
EOF

crontab -l \
    | grep -i settheme \
    | echo "$LINES" \
    | crontab -