#!/bin/bash
if [[ -n "$1" ]]; then
	primary="$1"
else
	primary=DP3
fi

if [[ "$2" -eq "vertical" ]]; then
	rel_direction=--below
else
	rel_direction=--left-of
fi

xrandr --output $primary --primary --mode 2560x1440 --rate 144 --output eDP1 --mode 1920x1200 $rel_direction $primary
