#!/bin/bash

playerctl --player playerctld "$1"

# # Outdated media controller for mpd and playerctl simultaneously,
# # without the use of mpDris2
# 
# altaction="$1"
# if [[ "$1" == "play-pause" ]]; then
	# altaction="toggle"
# fi
# 
# playerctl $1 || mpc $altaction
