#!/usr/bin/env bash
SRC="$HOME/scripts"
BIN="$HOME/.local/scripts"

if [ -d "$BIN" ]; then
    find "$BIN" -type l |
        while read LINK; do
            rm "$LINK"
        done
else
    mkdir -p "$BIN" || exit 1
fi

find "$SRC"/* -type d |
    while read DIR; do
        find -L "$DIR" -not -path '*/\.*' -type f |
            while read FILE; do
                ln -s "$FILE" "$BIN/$(basename $FILE)"
            done
    done

[ "$PATH" == *"$BIN"* ] || export PATH="$BIN:$PATH"
