#!/usr/bin/env bash

X_BASE="/etc/X11/xorg.conf.d"
F_CONF="$X_BASE/.20-egpu.conf"
F_ENABLED="$X_BASE/20-egpu.conf"

err() {
    echo "$1"
    exit $2
}

[ -n "$1" ] || err "Bus ID must be specified in format \`xx:yy.z'. Exiting..." 1
EXT_BUSID="$1"

enable() {
    if [ ! -f "$F_CONF" ]; then
        err "No config found at $F_CONF, exiting..." 1
    elif [ "$(readlink -- "$F_ENABLED")" == "$F_CONF" ]; then
        echo "eGPU configuration already active."
    else
        ln -s "$F_CONF" "$F_ENABLED" && echo "X config enabled."
    fi
}

disable() {
    if [ -f "$F_ENABLED" ]; then
        [ "$(readlink -- "$F_ENABLED")" == "$F_CONF" ] \
            || err "\`$F_ENABLED' is not a symlink to \`$F_CONF', exiting..." 1

        rm "$F_ENABLED"
    else
        echo "No active eGPU configuration found."
    fi
}

echo "Scanning for bus ID $EXT_BUSID..."
lspci -s "$EXT_BUSID" | grep "^$EXT_BUSID VGA compatible controller.*" >/dev/null
if [ $? == 0 ]; then
    echo "Enabling external graphics via xorg.conf.d..."
    enable
else
    echo "No eGPU found... resetting xorg configuration..."
    disable
fi