#!/usr/bin/env bash

# i3wm autostart script

LOC=$(cat "$XDG_CONFIG_HOME/locations/current")
LOCSTRING="$(echo $LOC | fmt_helio_location)"

XRES="$HOME/.Xresources"
LIBINPUTG="$(which libinput-gestures)"

update-scripts

if [ -f "$XRES" ]; then
    xrdb -merge "$XRES";
fi
    
if [ ! -f "$RANDR_LOCK" ]; then
    xrandr --auto
    autorandr -c
fi

relaunch picom      --config $XDG_CONFIG_HOME/picom/picom.conf &
relaunch polybar    main -c $XDG_CONFIG_HOME/polybar/config.ini &

relaunch python3 $LIBINPUTG &
relaunch playerctld         &
relaunch mpd-mpris          &
relaunch blueman-applet     &
relaunch xsettingsd         &
relaunch schedule_themes    &

if [ ! -f "/run/user/$UID/disable-lock.lock" ]; then
    relaunch enable-lock &
fi
    

if [ -x "$HOME/.fehbg" ]; then
    $HOME/.fehbg
fi
    
if [ -n "$LOC" ]; then
    relaunch redshift -l $LOC -m randr &
fi

firefox_static_location