#!/usr/bin/env bash

# $1 ...: command to relaunch
fproc() { pgrep -fx -u $USER "$ARGS" || pgrep -u $USER "$1"; };

ARGS="$@"
LIST=$(fproc $1)
if [ -n "$LIST" ]; then
	for proc in "$LIST"; do
		kill $proc
	done
	
	while fproc $1 >/dev/null;
	    do sleep 0.5; done
fi

$@
exit $?