#!/usr/bin/env bash

LOCKER=xss-lock
set LOCKPID
ps -C $LOCKER >/dev/null && LOCKPID=$(pgrep $LOCKER | tail -n1) || true

xset -dpms
xset s off
[ -n "${LOCKPID-}" ] && kill -SIGKILL $LOCKPID

trap restore SIGINT

restore() {
	physlock -L
	[ -n "${LOCKPID-}" ] && enable-lock || disable-lock
	exit
}

startlock() {
	physlock -l
	sxlock -f "Gohu GohuFont" &
}

startlock
if [ -e /dev/fd/${XSS_SLEEP_LOCK_FD:--1} ]; then
    exec {XSS_SLEEP_LOCK_FD}<&-
# else
    # xset dpms force suspend
fi

wait; restore