#!/usr/bin/env bash

HOSTNAME=AMIGA
SHARENAME=All
SUBNET=5
USERNAME="kwiggins"
PASSWORD="a3tEr01Ds"
MNTPOINT=/run/media/$USER/Amiga

echo "Scanning subnet $SUBNET for host '$HOSTNAME'..."
ADDR=$(sudo nbtscan -r 192.168.$SUBNET.0/24 -s ' ' \
		| grep -E ".* $HOSTNAME" | cut -d ' ' -f1)

if [ -n "$ADDR" ]; then
	echo "Found host '$HOSTNAME' at $ADDR"
	
	if [ ! -d "$MNTPOINT" ]; then
		sudo mkdir -p "$MNTPOINT" && sudo chown $USER:$USER "$MNTPOINT"
	elif mountpoint -q "$MNTPOINT"; then
		sudo umount "$MNTPOINT"
	fi
	
	if [ $? == 0 ]; then
		ARGS=$(printf '%s' \
			"-t cifs \
			-o username='$USERNAME',password='$PASSWORD'," \
			"uid=$UID,gid=$UID,file_mode=0775,dir_mode=0775," \
			"vers=1.0 \
			//$ADDR/$SHARENAME \
			$MNTPOINT")
		
		echo mount options: $ARGS
		sudo mount $ARGS && echo "Mounted '//$ADDR/$SHARENAME' at '$MNTPOINT'"
	else
		echo "Unable to create mount point"; exit $?
	fi
else
	echo "Unable to find address of host."
	exit 1
fi